### ISSUE TITLE
How to build docker from given virtualbox image?

### ISSUE THREAD

**Issue by Sunny-Island** [VidocqH/CS144_Introduction_to_Computer_Networking#1]
I just want to begin this course, and I want to use docker instead of virtual box. What should I do to build proper docker image for course project?

**Comment by VidocqH** [comment]
> I just want to begin this course, and I want to use docker instead of virtual box. What should I do to build proper docker image for course project?

直接从virtualbox image里整我也不知道行不行哈哈哈哈, 我是自己一个一个往里加进去的.
用我这个的话就image直接`docker pull vidocqh/cs144:latest`, 然后`docker run -it --name cs144 vidocqh/cs144:latest`就行.
之后再次进入就`docker exec -it cs144 bash`就成
Lab4和Lab5(我没记错的话是这两个)要修改一下`tun.sh`和`tap.sh`, 按照此库里的方式改就OK了.(到了Lab4再改也不迟)

**Comment by Sunny-Island** [comment]
如果我clone Sponge，再按你的dockerfile自己build一个是不是跟你的docker一样了

**Comment by Sunny-Island** [comment]
请问进入容器之后，怎么找到Sponge文件夹呢

**Comment by VidocqH** [comment]
> 请问进入容器之后，怎么找到Sponge文件夹呢

两个选择
1. 在容器里clone，需ssh到容器里编辑代码
2. 使用flag`-v`把本地sponge文件夹绑定到容器里，直接修改代码，容器里的sponge和本地的sponge是同一个文件夹

**Comment by Sunny-Island** [comment]
感谢回答！非常有帮助
