### ISSUE TITLE
关于tuntap的问题

### ISSUE THREAD

**Issue by Sunny-Island** [VidocqH/CS144_Introduction_to_Computer_Networking#2]
做到Lab4的时候，按照你的仓库改了tun.sh之后，会报找不到/dev/net/tun。
我执行了 mknod /dev/net/tun c 10 200 造出了和设备关联的tun，但执行相关命令第一句ip tuntap add mode tun user root name "${TUNDEV}"就提示 ioctl(TUNSETIFF): Operation not permitted。 docker里没有sudo，想问你当时是怎么解决这个问题的

**Comment by Sunny-Island** [comment]
你是怎么安装tuntap的呢？

**Comment by VidocqH** [comment]
`docker run -td --privileged --name cs144_container vidocqh/cs144`

**Comment by Sunny-Island** [comment]
/dev/net/tun不存在，也可以通过这种方式解决吗

**Comment by VidocqH** [comment]
正常运行的话，/dev/net/tun是会存在的。
你用这条指令重新run一个container，应该就没有问题了，我刚试了试，没有问题。

**Comment by Sunny-Island** [comment]
成功了，谢谢
